### ISSUE TITLE
Stop propagation

### ISSUE THREAD

**Issue by yura-moryliak** [iDGE90/fly-select#1]
Hello!
It would be nice to add stop propagation for keyboard navigation!
When i start to navigate with ArrowUp or ArrowDown it scrolls whole document body accordingly with a list of options!

And next few small issues:
1) Selected option is not highlighted and after second opening it does not show selected position in a list
2) Default option is not highlighted in a list

Cheers :)

**Comment by iDGE90** [comment]
Thanks for the feedback @yura-moryliak , all points you mention are valid. I'll update as soon as i have free time.
Cheers

**Comment by iDGE90** [comment]
Changes implemented.
